### PR TITLE
Fix README

### PR DESCRIPTION
**Pull request by emilfrolov**
I forgot to remove some "}" in README file

### CODE REVIEW

**Comment by CrocoDillon** [comment]
Hehe, can happen. What is that `.idea/watcherTasks.xml` file?

**Comment by emilfrolov** [comment]
Oh, it's my webstorm config file. I will remove it and resend PR

**Comment by emilfrolov** [comment]
Ready. I have removed config file.

**Comment by CrocoDillon** [comment]
Thanks! :shipit:

**Pull request merged**
